/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;

    
/**
 *
 * @author pikip
 */
public class Home extends javax.swing.JPanel {
    
    private final JPanel PanelBody;
    private final int categoria;
    private final String[] rutaImg;
    private String nombreGrupo;

    
    // Crear instancias de Dimension
    private final Dimension dimension = new Dimension(381, 291); 
    private final Dimension dimensionMax = new Dimension(431, 341); 
    
  
    /** 
     * Creates new form Home
     * @param panelBody
     * @param PanelBody
     * @param indice
     */
    public Home(JPanel panelBody, int indice) {
        this.PanelBody = panelBody;
        this.categoria = indice;
        initComponents(); 
        
        // Accedemos al array "grados" y al primer objeto dentro de ese array
           Object nombreGrupo = Json3.acceder("grados", String.valueOf(indice), "nombre");
           System.out.println("Nombre del grado cargado: " + nombreGrupo);
           
          
        // Asignar los labels de imágenes
        JLabel[] images = new JLabel [] {ImgHome1, ImgHome2, ImgHome3, ImgHome4, ImgHome5, ImgHome6};

        // Usar el nombre dinámico en la función CreateStringList
        rutaImg = Utilidades.CreateStringList("src/images/pics", nombreGrupo.toString(), "png", images.length).toArray(String[]::new);
        
        

            for (int i = 0; i < rutaImg.length; i++){
                final int finalIndex = i;
                //asignar imagen ruta correspondiente con label correspondiente
                Utilidades.SetImageLabel(images[i], rutaImg[i], dimension, true);
                //asignar eventos a cada label correspondiente
                images[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    // Acción al hacer clic
                    Game gm = new Game(finalIndex, categoria);
                    Utilidades.ShowPanel(PanelBody, gm);
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        // Acción al pasar el mouse sobre el JLabel
                        Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimensionMax, true);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        // Acción al salir el mouse del JLabel
                        Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimension, true);
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        // Acción al presionar el mouse sobre el JLabel
                        Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimension, true);
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        // Acción al liberar el mouse sobre el JLabel
                        Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimensionMax, true);
                    }
                });         
            }        
    }

  
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgHome1 = new javax.swing.JLabel();
        ImgHome2 = new javax.swing.JLabel();
        ImgHome3 = new javax.swing.JLabel();
        ImgHome4 = new javax.swing.JLabel();
        ImgHome5 = new javax.swing.JLabel();
        ImgHome6 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1550, 880));
        setMinimumSize(new java.awt.Dimension(1550, 880));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1550, 880));
        setLayout(new java.awt.GridLayout(2, 3, -100, -50));

        ImgHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado0.png"))); // NOI18N
        add(ImgHome1);

        ImgHome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado1.png"))); // NOI18N
        ImgHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(ImgHome2);

        ImgHome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado2.png"))); // NOI18N
        add(ImgHome3);

        ImgHome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado3.png"))); // NOI18N
        add(ImgHome4);

        ImgHome5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado4.png"))); // NOI18N
        add(ImgHome5);

        ImgHome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgHome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado5.png"))); // NOI18N
        add(ImgHome6);
    }// </editor-fold>//GEN-END:initComponents

    
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgHome1;
    private javax.swing.JLabel ImgHome2;
    private javax.swing.JLabel ImgHome3;
    private javax.swing.JLabel ImgHome4;
    private javax.swing.JLabel ImgHome5;
    private javax.swing.JLabel ImgHome6;
    // End of variables declaration//GEN-END:variables

   

}

    
   
   
   

