/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.json.JSONException;
import paquete.Json3;
import paquete.Utilidades;


    

/**0
 *
 * @author pikip
 */
    public final class Main extends javax.swing.JFrame {
    public static Main instance;

     
    Dimension dimension = new Dimension (100,100);
    
    
    /**
     * Creates new form Main
     * @throws java.io.IOException
     */
    public Main() throws IOException, JSONException {
        initComponents();
        
        // Llamada a la función para buscar todos los titulos de todos los juegos
//        Json.Json(); 
        
         // Llamada a la función para buscar un juego por título en JSON
//        Json2.buscarJuegoPorTitulo(); 
        
         // Llamada a la función para buscar un juego por índice en JSON
         ////Leer JSON desde el archivo
        Json3.cargarJSON("src/bbdd/BaseDeDatos.json");

     
        Home hm = new Home(PanelBody,0);
        Utilidades.ShowPanel(PanelBody, hm);
        
        iconos = new JLabel[] {Icono1, Icono2, Icono3, Icono4, Icono5, Icono6, Icono7, Icono8, Icono9, Icono10,Icono11 ,Icono12, Icono13, Icono14};
        rutas = Utilidades.CreateStringList("src/images/pics", "LauncherButton", "png", iconos.length).toArray(String[]::new);
           
        
       
        
        for (int i = 0; i < rutas.length; i++){
            final int finalIndex = i;
            //asignar imagen ruta correspondiente con label correspondiente
            Utilidades.SetImageLabel(iconos[i], rutas[i], dimension, true);
            //asignar eventos a cada label correspondiente
            iconos[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                // Acción al hacer clic
                Home hm = new Home(PanelBody, finalIndex);
                Utilidades.ShowPanel(PanelBody, hm);
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    // Acción al pasar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(iconos[finalIndex], rutas[finalIndex], true);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    // Acción al salir el mouse del JLabel
                    Utilidades.SetImageLabel(iconos[finalIndex], rutas[finalIndex], dimension, true);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    // Acción al presionar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(iconos[finalIndex], rutas[finalIndex],dimension, true);
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    // Acción al liberar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(iconos[finalIndex], rutas[finalIndex], true);
                }
            });
        }
       
                
        //Mostrar el fondo base
        LabelBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Fondo base.png")));
        LabelBase.setBounds(0, 0, 1920, 1080); // Establece el tamaño adecuado
        PanelBase.add(LabelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
        
        instance = this;
    }
    
    // Función genérica para imprimir cualquier campo del juego
    public Object imprimirCampo(String indiceHome, String indiceGame, String key) {
        Object valor = Json3.acceder("grados", indiceHome, "juegos", indiceGame, key);

        if (valor != null) {
            System.out.println(key.substring(0, 1).toUpperCase() + key.substring(1) + " del juego [" + indiceHome + "][" + indiceGame + "]: " + valor);
        } else {
            System.out.println("No se encontró el campo: " + key + " para el juego [" + indiceHome + "][" + indiceGame + "]");
        }

        return valor;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelHeader = new javax.swing.JPanel();
        Icono1 = new javax.swing.JLabel();
        Icono2 = new javax.swing.JLabel();
        Icono3 = new javax.swing.JLabel();
        Icono4 = new javax.swing.JLabel();
        Icono5 = new javax.swing.JLabel();
        Icono6 = new javax.swing.JLabel();
        Icono7 = new javax.swing.JLabel();
        Icono8 = new javax.swing.JLabel();
        Icono9 = new javax.swing.JLabel();
        Icono10 = new javax.swing.JLabel();
        Icono11 = new javax.swing.JLabel();
        Icono12 = new javax.swing.JLabel();
        Icono13 = new javax.swing.JLabel();
        Icono14 = new javax.swing.JLabel();
        PanelBody = new javax.swing.JPanel();
        LabelBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);

        PanelBase.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PanelBase.setMinimumSize(new java.awt.Dimension(1920, 1080));
        PanelBase.setOpaque(false);
        PanelBase.setPreferredSize(new java.awt.Dimension(1920, 1080));
        PanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeader.setOpaque(false);
        PanelHeader.setLayout(new java.awt.GridLayout(1, 0));

        Icono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton0.png"))); // NOI18N
        Icono1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono1);

        Icono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton1.png"))); // NOI18N
        Icono2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono2);

        Icono3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton2.png"))); // NOI18N
        Icono3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono3);

        Icono4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton3.png"))); // NOI18N
        Icono4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono4);

        Icono5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton4.png"))); // NOI18N
        Icono5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono5);

        Icono6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton5.png"))); // NOI18N
        Icono6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono6);

        Icono7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton6.png"))); // NOI18N
        Icono7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono7);

        Icono8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton7.png"))); // NOI18N
        Icono8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono8);

        Icono9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton8.png"))); // NOI18N
        Icono9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono9);

        Icono10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton9.png"))); // NOI18N
        Icono10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono10);

        Icono11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton10.png"))); // NOI18N
        Icono11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono11);

        Icono12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton11.png"))); // NOI18N
        Icono12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono12);

        Icono13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton12.png"))); // NOI18N
        Icono13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono13);

        Icono14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/LauncherButton13.png"))); // NOI18N
        Icono14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icono14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelHeader.add(Icono14);

        PanelBase.add(PanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 1500, 130));

        PanelBody.setMaximumSize(new java.awt.Dimension(1550, 880));
        PanelBody.setMinimumSize(new java.awt.Dimension(1550, 880));
        PanelBody.setOpaque(false);
        PanelBody.setLayout(new java.awt.BorderLayout());
        PanelBase.add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 1550, 890));

        LabelBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Fondo base.png"))); // NOI18N
        LabelBase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelBase.add(LabelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JSONException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            public void buscarJuegoPorTitulo() throws IOException {
                try {
                    Json2.buscarJuegoPorTitulo(); // Llamada a la función en la clase Json
                } catch (IOException e) {
                    System.err.println("Error al leer el archivo JSON: " + e.getMessage());
            }
        }
        });
    }

    JLabel[] iconos;
    String[] rutas;
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono1;
    private javax.swing.JLabel Icono10;
    private javax.swing.JLabel Icono11;
    private javax.swing.JLabel Icono12;
    private javax.swing.JLabel Icono13;
    private javax.swing.JLabel Icono14;
    private javax.swing.JLabel Icono2;
    private javax.swing.JLabel Icono3;
    private javax.swing.JLabel Icono4;
    private javax.swing.JLabel Icono5;
    private javax.swing.JLabel Icono6;
    private javax.swing.JLabel Icono7;
    private javax.swing.JLabel Icono8;
    private javax.swing.JLabel Icono9;
    private javax.swing.JLabel LabelBase;
    private javax.swing.JPanel PanelBase;
    public javax.swing.JPanel PanelBody;
    private javax.swing.JPanel PanelHeader;
    // End of variables declaration//GEN-END:variables

   
}
